import{i as c,S as l}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const d="45131715-e5faad2363c262c92b6a5cfbe",f="https://pixabay.com/api/";async function u(n){try{const t=await fetch(`${f}?key=${d}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`);if(!t.ok)throw new Error("Network response was not ok");return await t.json()}catch(t){throw console.error("Error fetching images:",t),t}}let a;function m(){document.getElementById("loading-indicator").classList.remove("hidden")}function y(){document.getElementById("loading-indicator").classList.add("hidden")}function p(){document.getElementById("gallery").innerHTML=""}function g(n){const t=document.getElementById("gallery");if(n.length===0){c.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}const i=n.map(o=>`
        <a class="gallery-item" href="${o.largeImageURL}">
            <img src="${o.webformatURL}" alt="${o.tags}" />
            <div class="info">
                <p>Likes: ${o.likes}</p>
                <p>Views: ${o.views}</p>
                <p>Comments: ${o.comments}</p>
                <p>Downloads: ${o.downloads}</p>
            </div>
        </a>
    `).join("");t.innerHTML=i,a&&a.destroy(),a=new l(".gallery-item a",{captionsData:"alt",captionDelay:250})}document.getElementById("search-form").addEventListener("submit",async n=>{n.preventDefault();const t=document.getElementById("search-query").value.trim();if(!t){iziToast.error({title:"Error",message:"Search field cannot be empty"});return}m();try{const i=await u(t);p(),g(i.hits)}catch{iziToast.error({title:"Error",message:"An error occurred while fetching data."})}finally{y()}});
//# sourceMappingURL=commonHelpers.js.map
